//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSEU.Application.Common.Resources.Attachments {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkflowAttachmentsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkflowAttachmentsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSEU.Application.Common.Resources.Attachments.WorkflowAttachmentsResource", typeof(WorkflowAttachmentsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ на ознакомление.
        /// </summary>
        public static string AcquaintanceDocument {
            get {
                return ResourceManager.GetString("AcquaintanceDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложения.
        /// </summary>
        public static string AcquaintanceDocumentAddendums {
            get {
                return ResourceManager.GetString("AcquaintanceDocumentAddendums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложений к документу нет.
        /// </summary>
        public static string AcquaintanceDocumentAddendumsDescription {
            get {
                return ResourceManager.GetString("AcquaintanceDocumentAddendumsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительно.
        /// </summary>
        public static string AcquaintanceDocumentAdditionaly {
            get {
                return ResourceManager.GetString("AcquaintanceDocumentAdditionaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вложений нет.
        /// </summary>
        public static string AcquaintanceDocumentAdditionalyDescription {
            get {
                return ResourceManager.GetString("AcquaintanceDocumentAdditionalyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ не вложен.
        /// </summary>
        public static string AcquaintanceDocumentDescription {
            get {
                return ResourceManager.GetString("AcquaintanceDocumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ для исполнения.
        /// </summary>
        public static string ActionItemExecutionDocument {
            get {
                return ResourceManager.GetString("ActionItemExecutionDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложения.
        /// </summary>
        public static string ActionItemExecutionDocumentAddendums {
            get {
                return ResourceManager.GetString("ActionItemExecutionDocumentAddendums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложения к документу отсутствуют.
        /// </summary>
        public static string ActionItemExecutionDocumentAddendumsDescription {
            get {
                return ResourceManager.GetString("ActionItemExecutionDocumentAddendumsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительно.
        /// </summary>
        public static string ActionItemExecutionDocumentAdditionaly {
            get {
                return ResourceManager.GetString("ActionItemExecutionDocumentAdditionaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вложите сопроводительные материалы к исполняемому документу.
        /// </summary>
        public static string ActionItemExecutionDocumentAdditionalyDescription {
            get {
                return ResourceManager.GetString("ActionItemExecutionDocumentAdditionalyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ не вложен.
        /// </summary>
        public static string ActionItemExecutionDocumentDescription {
            get {
                return ResourceManager.GetString("ActionItemExecutionDocumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты исполнения.
        /// </summary>
        public static string ActionItemExecutionDocumentResult {
            get {
                return ResourceManager.GetString("ActionItemExecutionDocumentResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вложите результат исполнения поручения, если необходимо.
        /// </summary>
        public static string ActionItemExecutionDocumentResultDescription {
            get {
                return ResourceManager.GetString("ActionItemExecutionDocumentResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты исполнения.
        /// </summary>
        public static string ActionItemExecutionResult {
            get {
                return ResourceManager.GetString("ActionItemExecutionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложения.
        /// </summary>
        public static string Addendums {
            get {
                return ResourceManager.GetString("Addendums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительно.
        /// </summary>
        public static string Additionaly {
            get {
                return ResourceManager.GetString("Additionaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вложения.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ на рассмотрение.
        /// </summary>
        public static string DocumentReview {
            get {
                return ResourceManager.GetString("DocumentReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложения.
        /// </summary>
        public static string DocumentReviewAddendums {
            get {
                return ResourceManager.GetString("DocumentReviewAddendums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложения к документу отсутствуют.
        /// </summary>
        public static string DocumentReviewAddendumsDescription {
            get {
                return ResourceManager.GetString("DocumentReviewAddendumsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительно.
        /// </summary>
        public static string DocumentReviewAdditionaly {
            get {
                return ResourceManager.GetString("DocumentReviewAdditionaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DocumentReviewAdditionalyDescriptioon {
            get {
                return ResourceManager.GetString("DocumentReviewAdditionalyDescriptioon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вложите документ на рассмотрение.
        /// </summary>
        public static string DocumentReviewDescription {
            get {
                return ResourceManager.GetString("DocumentReviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На согласование.
        /// </summary>
        public static string FreeApprovalDocument {
            get {
                return ResourceManager.GetString("FreeApprovalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вложений нет.
        /// </summary>
        public static string NoAttachments {
            get {
                return ResourceManager.GetString("NoAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект резолюции.
        /// </summary>
        public static string Resoulution {
            get {
                return ResourceManager.GetString("Resoulution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string ResoulutionDescription {
            get {
                return ResourceManager.GetString("ResoulutionDescription", resourceCulture);
            }
        }
    }
}
