version: '3.7'

services:
   postgresdb:
    container_name: postgresdb
    image: postgres:latest
    restart: always

   pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    restart: always

   elasticsearch:
    container_name: elasticsearch
    image: elasticsearch_plugins:7.11.2
    restart: always

   kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.2
    restart: always

volumes:
  postgres-db-data:
  pgAdmin-data:
  elasticsearch-data:
  kibana-data: