version: '3.7'

services:
   postgresdb:
    container_name: postgresdb
    image: postgres:latest
    restart: always

   pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    restart: always

   elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    restart: always

volumes:
  postgres-db-data:
  pgAdmin-data:
  elasticsearch-data: