version: '3.4'

services:
  dseu:
    environment:
      - ConnectionStrings__DefaultConnection=Server=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password1!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - WAIT_HOSTS=${APP_WAIT_HOSTS}
      - Organization__Name=Dseu
    ports:
      - 443:443
    networks:
      - dseu-network
    volumes:
      - ./certs/app:/https:ro
      - ./config:/config:ro
    command: sh -c "dotnet DSEU.UI.dll" 