version: '3.4'

services:
   postgresdb:
    ports:
     - 5432:5432 
    volumes:
     - postgres-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
     - dseu-network

   pgAdmin:
    ports:
     - 5151:80
    volumes:
     - pgAdmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks: 
     - dseu-network

   elasticsearch:
    ports:
     - 9200:9200
     - 9300:9300
    volumes:
     - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
     - xpack.security.enabled=false
     - discovery.type=single-node
    networks:
     - dseu-network
   