// <auto-generated />
using System;
using DSEU.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DSEU.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210309054833_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DSEU.Domain.Entities.AppInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InstalledVersion")
                        .HasColumnType("text");

                    b.Property<string>("MainLanguage")
                        .HasColumnType("text");

                    b.Property<string>("MigrationName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppInfo");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.Commons.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AlphaCode")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("FractionName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NumericCode")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.Commons.TerritorialUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.HasIndex("TypeId");

                    b.ToTable("TerritorialUnit");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.Commons.TerritorialUnitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TerritorialUnitType");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.Company.OrganizationalUnitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OrganizationalUnitType");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.CoreEntities.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AuthenticationType")
                        .HasColumnType("integer");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoginName")
                        .IsUnique();

                    b.ToTable("Login");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.CoreEntities.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecipientType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Description");

                    b.HasIndex("Name");

                    b.ToTable("Recipient");

                    b.HasDiscriminator<int>("RecipientType");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.OurOrganization.JobTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JobTitle");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.OurOrganization.OrganizationalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TypeId");

                    b.ToTable("OrganizationalUnit");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstateRights.BasisForChangeDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RealEstateRightId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RealEstateRightId");

                    b.ToTable("BasisForChangeDocument");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BasisForChangeDocument");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstateRights.RealEstateRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("RealEstateId")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewResult")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StatementDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("RealEstateId");

                    b.ToTable("RealEstateRight");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RealEstateRight");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstates.RealEstate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<decimal?>("CadastralCost")
                        .HasColumnType("numeric");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DealCost")
                        .HasColumnType("numeric");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("RealEstate");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RealEstate");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.SubjectsOfRights.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Citizenship")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int>("IdentityDocumentType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("text");

                    b.Property<string>("Registration")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Applicant");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.CoreEntities.Role", b =>
                {
                    b.HasBaseType("DSEU.Domain.Entities.CoreEntities.Recipient");

                    b.Property<bool>("Immutable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSingleUser")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("DSEU.Domain.Entities.CoreEntities.User", b =>
                {
                    b.HasBaseType("DSEU.Domain.Entities.CoreEntities.Recipient");

                    b.Property<int?>("LoginId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<byte[]>("PersonalPhoto")
                        .HasColumnType("bytea");

                    b.Property<string>("PersonalPhotoHash")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstateRights.Deal", b =>
                {
                    b.HasBaseType("DSEU.Domain.Entities.RealEstateRights.BasisForChangeDocument");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<double>("Cost")
                        .HasColumnType("double precision");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasIndex("CurrencyId");

                    b.HasDiscriminator().HasValue("Deal");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstateRights.LawEstablishingDocument", b =>
                {
                    b.HasBaseType("DSEU.Domain.Entities.RealEstateRights.BasisForChangeDocument");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("LawEstablishingDocument");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstateRights.SpecifyingDocument", b =>
                {
                    b.HasBaseType("DSEU.Domain.Entities.RealEstateRights.BasisForChangeDocument");

                    b.HasDiscriminator().HasValue("SpecifyingDocument");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstateRights.RealEstateOwnRight", b =>
                {
                    b.HasBaseType("DSEU.Domain.Entities.RealEstateRights.RealEstateRight");

                    b.HasDiscriminator().HasValue("RealEstateOwnRight");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstates.Building", b =>
                {
                    b.HasBaseType("DSEU.Domain.Entities.RealEstates.RealEstate");

                    b.Property<int?>("AboveGroundFloorsCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ApartmentNumber")
                        .HasColumnType("integer");

                    b.Property<double?>("CommonSquare")
                        .HasColumnType("double precision");

                    b.Property<int?>("Flat")
                        .HasColumnType("integer");

                    b.Property<int?>("FlatTotal")
                        .HasColumnType("integer");

                    b.Property<string>("InvertarNumber")
                        .HasColumnType("text");

                    b.Property<double?>("LiveSquare")
                        .HasColumnType("double precision");

                    b.Property<int?>("RoomTotal")
                        .HasColumnType("integer");

                    b.Property<int?>("UndergroundFloorsCount")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Building");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstates.Land", b =>
                {
                    b.HasBaseType("DSEU.Domain.Entities.RealEstates.RealEstate");

                    b.Property<string>("CadastralNumber")
                        .HasColumnType("text");

                    b.Property<double>("Square")
                        .HasColumnType("double precision");

                    b.Property<string>("VirtualCadastralNumber")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Land");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.CoreEntities.SystemUser", b =>
                {
                    b.HasBaseType("DSEU.Domain.Entities.CoreEntities.User");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("DSEU.Domain.Entities.Persons.Employee", b =>
                {
                    b.HasBaseType("DSEU.Domain.Entities.CoreEntities.User");

                    b.Property<DateTime?>("DateOfAppointment")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateOfDismissal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int?>("JobTitleId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int?>("OrganizationalUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int?>("Sex")
                        .HasColumnType("integer");

                    b.HasIndex("JobTitleId");

                    b.HasIndex("OrganizationalUnitId");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("DSEU.Domain.Entities.Commons.TerritorialUnit", b =>
                {
                    b.HasOne("DSEU.Domain.Entities.Commons.TerritorialUnit", "Parent")
                        .WithMany("Childs")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DSEU.Domain.Entities.Commons.TerritorialUnitType", "Type")
                        .WithMany("TerritorialUnits")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.OurOrganization.OrganizationalUnit", b =>
                {
                    b.HasOne("DSEU.Domain.Entities.OurOrganization.OrganizationalUnit", "Parent")
                        .WithMany("Childs")
                        .HasForeignKey("ParentId");

                    b.HasOne("DSEU.Domain.Entities.Company.OrganizationalUnitType", "Type")
                        .WithMany("OrganizationalUnits")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstateRights.BasisForChangeDocument", b =>
                {
                    b.HasOne("DSEU.Domain.Entities.RealEstateRights.RealEstateRight", "RealEstateRight")
                        .WithMany("Documents")
                        .HasForeignKey("RealEstateRightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealEstateRight");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstateRights.RealEstateRight", b =>
                {
                    b.HasOne("DSEU.Domain.Entities.SubjectsOfRights.Applicant", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId");

                    b.HasOne("DSEU.Domain.Entities.RealEstates.RealEstate", "RealEstate")
                        .WithMany("Rights")
                        .HasForeignKey("RealEstateId");

                    b.Navigation("Applicant");

                    b.Navigation("RealEstate");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstates.RealEstate", b =>
                {
                    b.HasOne("DSEU.Domain.Entities.Commons.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.CoreEntities.User", b =>
                {
                    b.HasOne("DSEU.Domain.Entities.CoreEntities.Login", "Login")
                        .WithOne()
                        .HasForeignKey("DSEU.Domain.Entities.CoreEntities.User", "LoginId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstateRights.Deal", b =>
                {
                    b.HasOne("DSEU.Domain.Entities.Commons.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.Persons.Employee", b =>
                {
                    b.HasOne("DSEU.Domain.Entities.OurOrganization.JobTitle", "JobTitle")
                        .WithMany("Employees")
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DSEU.Domain.Entities.OurOrganization.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany()
                        .HasForeignKey("OrganizationalUnitId");

                    b.Navigation("JobTitle");

                    b.Navigation("OrganizationalUnit");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.Commons.TerritorialUnit", b =>
                {
                    b.Navigation("Childs");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.Commons.TerritorialUnitType", b =>
                {
                    b.Navigation("TerritorialUnits");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.Company.OrganizationalUnitType", b =>
                {
                    b.Navigation("OrganizationalUnits");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.OurOrganization.JobTitle", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.OurOrganization.OrganizationalUnit", b =>
                {
                    b.Navigation("Childs");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstateRights.RealEstateRight", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("DSEU.Domain.Entities.RealEstates.RealEstate", b =>
                {
                    b.Navigation("Rights");
                });
#pragma warning restore 612, 618
        }
    }
}
